#!/usr/bin/env python3
"""
DayTrader v2 — Environment Setup
Creates a .env file with Alpaca API credentials.

Usage:
  python setup_env.py
  python setup_env.py --paper    (default - paper trading)
  python setup_env.py --live     (live trading - use with caution)
"""
import os
import sys
import getpass
from pathlib import Path


ENV_FILE = Path(__file__).parent / ".env"

PAPER_URL = "https://paper-api.alpaca.markets"
LIVE_URL = "https://api.alpaca.markets"


def main():
    mode = "paper"
    if "--live" in sys.argv:
        mode = "live"
        print("=" * 50)
        print("  WARNING: LIVE TRADING MODE")
        print("  Real money will be used for trades.")
        print("=" * 50)
        confirm = input("Type 'YES' to confirm live mode: ").strip()
        if confirm != "YES":
            print("Cancelled. Defaulting to paper trading.")
            mode = "paper"

    print()
    print("DayTrader v2 — Environment Setup")
    print("-" * 40)
    print(f"Mode: {'PAPER (simulated)' if mode == 'paper' else 'LIVE (real money)'}")
    print()
    print("Enter your Alpaca API credentials.")
    print("Get them at: https://app.alpaca.markets/paper/dashboard/overview")
    print("  (Paper keys are under Paper Trading > API Keys)")
    print()

    # Prompt for keys (masked input for secret)
    api_key = input("APCA_API_KEY_ID: ").strip()
    if not api_key:
        print("Error: API Key ID cannot be empty.")
        sys.exit(1)

    api_secret = getpass.getpass("APCA_API_SECRET_KEY (hidden): ").strip()
    if not api_secret:
        print("Error: API Secret Key cannot be empty.")
        sys.exit(1)

    # Data feed selection
    print()
    print("Data feed options:")
    print("  iex  — Free, 15-min delayed quotes (good for testing)")
    print("  sip  — Paid, real-time consolidated feed (recommended for trading)")
    feed = input("Data feed [iex]: ").strip().lower() or "iex"
    if feed not in ("iex", "sip"):
        print(f"Invalid feed '{feed}', defaulting to 'iex'")
        feed = "iex"

    # Build .env content
    base_url = PAPER_URL if mode == "paper" else LIVE_URL
    env_content = f"""# DayTrader v2 — Alpaca Configuration
# Generated by setup_env.py
# Mode: {mode.upper()}

# Alpaca API Credentials
APCA_API_KEY_ID={api_key}
APCA_API_SECRET_KEY={api_secret}

# Alpaca Base URL
APCA_API_BASE_URL={base_url}

# Data feed: 'iex' (free/delayed) or 'sip' (paid/real-time)
APCA_DATA_FEED={feed}

# Trading mode
DAYTRADER_MODE={mode}
DAYTRADER_DRY_RUN=false

# Optional: path to universe CSV (leave empty for default)
DAYTRADER_UNIVERSE=
"""

    # Check for existing .env
    if ENV_FILE.exists():
        print()
        overwrite = input(f".env already exists at {ENV_FILE}. Overwrite? [y/N]: ").strip().lower()
        if overwrite != "y":
            print("Cancelled. Existing .env unchanged.")
            sys.exit(0)

    # Write .env
    ENV_FILE.write_text(env_content)
    os.chmod(ENV_FILE, 0o600)  # restrict permissions to owner only
    print()
    print(f"Saved to: {ENV_FILE}")
    print(f"Permissions set to 600 (owner read/write only)")
    print()

    # Verify by loading
    print("Verifying credentials...")
    os.environ["APCA_API_KEY_ID"] = api_key
    os.environ["APCA_API_SECRET_KEY"] = api_secret
    os.environ["APCA_API_BASE_URL"] = base_url

    try:
        import requests
        resp = requests.get(
            f"{base_url}/v2/account",
            headers={
                "APCA-API-KEY-ID": api_key,
                "APCA-API-SECRET-KEY": api_secret,
            },
            timeout=10,
        )
        if resp.status_code == 200:
            acct = resp.json()
            equity = float(acct.get("equity", 0))
            bp = float(acct.get("buying_power", 0))
            status = acct.get("status", "unknown")
            print(f"  Connected successfully!")
            print(f"  Account status: {status}")
            print(f"  Equity:         ${equity:,.2f}")
            print(f"  Buying power:   ${bp:,.2f}")
        elif resp.status_code == 403:
            print(f"  ERROR: Authentication failed (403). Check your API keys.")
        else:
            print(f"  WARNING: Got status {resp.status_code}: {resp.text[:100]}")
    except ImportError:
        print("  (requests not installed — skipping verification)")
    except Exception as e:
        print(f"  WARNING: Could not verify: {e}")

    print()
    print("Setup complete! Next steps:")
    print("  1. Run dry-run:   python -m daytrader run --dry-run")
    print("  2. Run paper:     python -m daytrader run")
    print("  3. Run backtest:  python -m daytrader backtest --start 2025-01-02 --end 2025-01-31")


if __name__ == "__main__":
    main()
